#!/bin/bash

# Job name:
#SBATCH --job-name=ANGSD_SNP
#
# Project:
#SBATCH --account=nn9244k
#
# Wall clock limit:
#SBATCH --time=17:00:00
#
# Processor and memory usage:
#SBATCH --mem-per-cpu=5G
#
#SBATCH --ntasks-per-node=24


module load angsd/0.931-GCC-8.2.0-2.31.1

mkdir -p SNP_out
mkdir -p Freq_output

#angsd -out Freq_output/Freq_$1 -doMaf 8 -doCounts 1 -doMajorMinor 2 -bam $1 -ref /cluster/projects/nn9244k/databases/gadus_morhua/gadMor2/sep_mt_gen_nu_gen/gadMor2.nu.fasta -nThreads 4

angsd -b bam.list -anc /cluster/projects/nn9244k/databases/gadus_morhua/gadMor2/sep_mt_gen_nu_gen/gadMor2.nu.fasta \
-out SNP_out/SNP.test -dosaf 1 -GL 1 -doGlf 2 -doMaf 1 -doMajorMinor 1 \
-doPost 1 -doVcf 1 -doCounts 1 -doDepth 1 -dumpCounts 1 -doIBS 1 -makematrix 1 -doCov 1 -P 32 \
-SNP_pval 1e-6 -setMinDepth 300 -setMaxDepth 20000 \
-minInd 20 -minQ 20 -minMaf 0.01 \

##IF FINISHED THEN
zcat SNP_out/SNP.test.mafs.gz | cut -f 1,2,3,4 | tail -n +2 > SNP.list.txt

##INDEX
angsd sites index SNP.list.txt

##MODIFY SNP.list.txt (Nina protocol)
cut -f 1,2 SNP.list.txt | sed 's/\t/:/g' > SNP.list.regions
